const config = require('./config.json')
const colors = require('./colors')
const nodemailer = require('nodemailer');

var transporter = nodemailer.createTransport({
    service: "gmail",
    auth: {
        user: `${config["gmail-user"]}`,
        pass: `${config["gmail-app-password"]}`
    },
    tls: {
        rejectUnauthorized: false
    }
});

/**
 * 
 * @param {Email Message} message The raw JSON email message
 */

function send(message) {

    console.log(`[${new Date().toLocaleString()}] ${colors.cyan}Sending email ${colors.black}${colors.bright}(${message.subject})${colors.r}`)


    var mailOptions = {
        from: `Synergy Mailer <${config["gmail-user"]}>`,
        to: config["destination-emails"],
        subject: message.subject,
        text: `${message.messageText}\n—\nAdditional information\nFrom: ${message.from.contactDetails1} (${message.from.contactDetails2})\nSend Date Time: ${message.sendDateTimeFormattedLong}\nOrganization: ${message.from.organizationName}\nRead/Sent: ${message.readCount}/${message.personCount}\n—\nThis email was autogenerated by the StudentVue Mailer`,
        html: `<body>
        <div
            style="display:none; max-height:0px; max-width:0px; opacity:0; overflow:hidden;">
            You have a new StudentVue message! This message was generated from the StudentVue mail service.
        </div>
        <span>${message.messageText}</span>
        <div>
          <p style="font-size:small;-webkit-text-size-adjust:none;color:#666;">&mdash;<br />
            Additional information<br />
            From: ${message.from.contactDetails1} (${message.from.contactDetails2})<br />
            Send Date Time: ${message.sendDateTimeFormattedLong}<br />
            Organization: ${message.from.organizationName}<br />
            Read/Sent: ${message.readCount}/${message.personCount}<br />&mdash;
            <br />This email was autogenerated by the StudentVue Mailer<br />
          </p>
        </div>
    </body>`
    };

    return new Promise(function (resolve, reject) {
        transporter.sendMail(mailOptions, function (error, info) {
            if (error) {
                console.log(`[${new Date().toLocaleString()}] ` + error);
                reject()
            } else {
                console.log('Email sent: ' + info.response);
                resolve()
            }
        })
    })
}

module.exports = send;